// Code generated by protoc-gen-go. DO NOT EDIT.
// source: 1.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MyMessage struct {
	// Define the oneof field
	//
	// Types that are valid to be assigned to AllowedStrings:
	//	*MyMessage_FirstString
	//	*MyMessage_SecondString
	//	*MyMessage_ThirdString
	//	*MyMessage_FourthString
	AllowedStrings       isMyMessage_AllowedStrings `protobuf_oneof:"allowed_strings"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *MyMessage) Reset()         { *m = MyMessage{} }
func (m *MyMessage) String() string { return proto.CompactTextString(m) }
func (*MyMessage) ProtoMessage()    {}
func (*MyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_1895e6d44c6a5e97, []int{0}
}

func (m *MyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyMessage.Unmarshal(m, b)
}
func (m *MyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyMessage.Marshal(b, m, deterministic)
}
func (m *MyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyMessage.Merge(m, src)
}
func (m *MyMessage) XXX_Size() int {
	return xxx_messageInfo_MyMessage.Size(m)
}
func (m *MyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MyMessage proto.InternalMessageInfo

type isMyMessage_AllowedStrings interface {
	isMyMessage_AllowedStrings()
}

type MyMessage_FirstString struct {
	FirstString string `protobuf:"bytes,1,opt,name=first_string,json=firstString,proto3,oneof"`
}

type MyMessage_SecondString struct {
	SecondString string `protobuf:"bytes,2,opt,name=second_string,json=secondString,proto3,oneof"`
}

type MyMessage_ThirdString struct {
	ThirdString string `protobuf:"bytes,3,opt,name=third_string,json=thirdString,proto3,oneof"`
}

type MyMessage_FourthString struct {
	FourthString string `protobuf:"bytes,4,opt,name=fourth_string,json=fourthString,proto3,oneof"`
}

func (*MyMessage_FirstString) isMyMessage_AllowedStrings() {}

func (*MyMessage_SecondString) isMyMessage_AllowedStrings() {}

func (*MyMessage_ThirdString) isMyMessage_AllowedStrings() {}

func (*MyMessage_FourthString) isMyMessage_AllowedStrings() {}

func (m *MyMessage) GetAllowedStrings() isMyMessage_AllowedStrings {
	if m != nil {
		return m.AllowedStrings
	}
	return nil
}

func (m *MyMessage) GetFirstString() string {
	if x, ok := m.GetAllowedStrings().(*MyMessage_FirstString); ok {
		return x.FirstString
	}
	return ""
}

func (m *MyMessage) GetSecondString() string {
	if x, ok := m.GetAllowedStrings().(*MyMessage_SecondString); ok {
		return x.SecondString
	}
	return ""
}

func (m *MyMessage) GetThirdString() string {
	if x, ok := m.GetAllowedStrings().(*MyMessage_ThirdString); ok {
		return x.ThirdString
	}
	return ""
}

func (m *MyMessage) GetFourthString() string {
	if x, ok := m.GetAllowedStrings().(*MyMessage_FourthString); ok {
		return x.FourthString
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MyMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MyMessage_FirstString)(nil),
		(*MyMessage_SecondString)(nil),
		(*MyMessage_ThirdString)(nil),
		(*MyMessage_FourthString)(nil),
	}
}

func init() {
	proto.RegisterType((*MyMessage)(nil), "example.MyMessage")
}

func init() { proto.RegisterFile("1.proto", fileDescriptor_1895e6d44c6a5e97) }

var fileDescriptor_1895e6d44c6a5e97 = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x62, 0x37, 0xd4, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49, 0x55, 0xda, 0xc6, 0xc8,
	0xc5, 0xe9, 0x5b, 0xe9, 0x9b, 0x5a, 0x5c, 0x9c, 0x98, 0x9e, 0x2a, 0xa4, 0xcc, 0xc5, 0x93, 0x96,
	0x59, 0x54, 0x5c, 0x12, 0x5f, 0x5c, 0x52, 0x94, 0x99, 0x97, 0x2e, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1,
	0xe9, 0xc1, 0x10, 0xc4, 0x0d, 0x16, 0x0d, 0x06, 0x0b, 0x0a, 0xa9, 0x72, 0xf1, 0x16, 0xa7, 0x26,
	0xe7, 0xe7, 0xa5, 0xc0, 0x54, 0x31, 0x41, 0x55, 0xf1, 0x40, 0x84, 0xa1, 0xca, 0x94, 0xb9, 0x78,
	0x4a, 0x32, 0x32, 0x8b, 0xe0, 0xaa, 0x98, 0x61, 0x66, 0x81, 0x45, 0x11, 0x66, 0xa5, 0xe5, 0x97,
	0x16, 0x95, 0x64, 0xc0, 0x54, 0xb1, 0xc0, 0xcc, 0x82, 0x08, 0x43, 0x94, 0x39, 0x09, 0x72, 0xf1,
	0x27, 0xe6, 0xe4, 0xe4, 0x97, 0xa7, 0xc2, 0x4c, 0x2b, 0x76, 0xe2, 0x88, 0x62, 0xd3, 0xd3, 0x4f,
	0x2f, 0x2a, 0x48, 0x4e, 0x62, 0x03, 0x7b, 0xc9, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x06, 0x2d,
	0xfc, 0x30, 0xdd, 0x00, 0x00, 0x00,
}
